name: Tests
on:
  push:
    paths-ignore:
      - README.md
      - LICENSE.txt

jobs:
  test-runtimes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with: 
          distribution: 'zulu'
          java-version: '24'

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: 'latest'
          clj-kondo: 'latest'
          bb: 'latest'

      - name: Test Babashka
        run: |
          bb test:bb
        
      - name: Test Clojure
        run: |
          bb test:clj

      - name: Test ClojureScript
        run: |
          bb test:cljs

